import 'package:flutter_lifter/models/exercise_models.dart';
import 'package:flutter_lifter/models/shared_enums.dart';
import 'package:flutter_lifter/models/user_exercise_preferences.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('UserExercisePreferences', () {
    late Exercise testExercise;

    setUp(() {
      testExercise = Exercise(
        id: 'bench',
        name: 'Bench Press',
        category: ExerciseCategory.strength,
        targetMuscleGroups: ['Chest', 'Triceps'],
        defaultSets: 3,
        defaultReps: 8,
        defaultWeight: 135.0,
        defaultRestTimeSeconds: 120,
        isDefault: true,
      );
    });

    group('Constructor', () {
      test('should create with all required fields', () {
        final pref = UserExercisePreferences(
          id: 'pref_1',
          exerciseId: 'bench',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        expect(pref.id, equals('pref_1'));
        expect(pref.exerciseId, equals('bench'));
        expect(pref.preferredSets, isNull);
        expect(pref.preferredReps, isNull);
        expect(pref.preferredWeight, isNull);
        expect(pref.preferredRestTimeSeconds, isNull);
        expect(pref.notes, isNull);
      });

      test('should create with all optional fields', () {
        final pref = UserExercisePreferences(
          id: 'pref_1',
          exerciseId: 'bench',
          preferredSets: 5,
          preferredReps: 5,
          preferredWeight: 225.0,
          preferredRestTimeSeconds: 180,
          notes: 'Heavy day',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        expect(pref.preferredSets, equals(5));
        expect(pref.preferredReps, equals(5));
        expect(pref.preferredWeight, equals(225.0));
        expect(pref.preferredRestTimeSeconds, equals(180));
        expect(pref.notes, equals('Heavy day'));
      });
    });

    group('Factory Constructor - create', () {
      test('should auto-generate id and timestamps', () {
        final before = DateTime.now();

        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
        );

        final after = DateTime.now();

        expect(pref.id, isNotEmpty);
        // ID is generated by Utils.generateId() which uses timestamp format
        expect(pref.id.contains('_'), isTrue);
        expect(pref.exerciseId, equals('bench'));
        expect(pref.preferredSets, equals(5));

        // Check timestamps are reasonable
        expect(
            pref.createdAt.isAfter(before) ||
                pref.createdAt.isAtSameMomentAs(before),
            isTrue);
        expect(
            pref.createdAt.isBefore(after) ||
                pref.createdAt.isAtSameMomentAs(after),
            isTrue);
        expect(pref.updatedAt, equals(pref.createdAt));
      });

      test('should create with only exerciseId', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'squat',
        );

        expect(pref.exerciseId, equals('squat'));
        expect(pref.preferredSets, isNull);
        expect(pref.preferredReps, isNull);
        expect(pref.preferredWeight, isNull);
        expect(pref.preferredRestTimeSeconds, isNull);
        expect(pref.notes, isNull);
      });
    });

    group('hasPreferences', () {
      test('should return false when no preferences set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
        );

        expect(pref.hasPreferences, isFalse);
      });

      test('should return true when preferredSets is set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
        );

        expect(pref.hasPreferences, isTrue);
      });

      test('should return true when preferredReps is set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredReps: 10,
        );

        expect(pref.hasPreferences, isTrue);
      });

      test('should return true when preferredWeight is set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredWeight: 200.0,
        );

        expect(pref.hasPreferences, isTrue);
      });

      test('should return true when preferredRestTimeSeconds is set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredRestTimeSeconds: 90,
        );

        expect(pref.hasPreferences, isTrue);
      });

      test('should return true when notes is set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          notes: 'Some notes',
        );

        expect(pref.hasPreferences, isTrue);
      });

      test('should return true when multiple preferences are set', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
          preferredReps: 5,
          preferredWeight: 225.0,
        );

        expect(pref.hasPreferences, isTrue);
      });
    });

    group('applyToExercise', () {
      test('should apply preferredSets to exercise', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.defaultSets, equals(5));
        expect(modified.defaultReps, equals(8)); // unchanged
        expect(modified.defaultWeight, equals(135.0)); // unchanged
      });

      test('should apply preferredReps to exercise', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredReps: 12,
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.defaultReps, equals(12));
        expect(modified.defaultSets, equals(3)); // unchanged
      });

      test('should apply preferredWeight to exercise', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredWeight: 225.0,
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.defaultWeight, equals(225.0));
      });

      test('should apply preferredRestTimeSeconds to exercise', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredRestTimeSeconds: 180,
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.defaultRestTimeSeconds, equals(180));
      });

      test('should apply notes to exercise', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          notes: 'Focus on form',
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.notes, equals('Focus on form'));
      });

      test('should apply all preferences at once', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
          preferredReps: 5,
          preferredWeight: 315.0,
          preferredRestTimeSeconds: 240,
          notes: 'Heavy day',
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.defaultSets, equals(5));
        expect(modified.defaultReps, equals(5));
        expect(modified.defaultWeight, equals(315.0));
        expect(modified.defaultRestTimeSeconds, equals(240));
        expect(modified.notes, equals('Heavy day'));
      });

      test('should not modify original exercise', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 10,
        );

        pref.applyToExercise(testExercise);

        // Original should be unchanged
        expect(testExercise.defaultSets, equals(3));
      });

      test('should throw ArgumentError if exerciseId does not match', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'squat',
          preferredSets: 5,
        );

        expect(
          () => pref.applyToExercise(testExercise),
          throwsA(isA<ArgumentError>()),
        );
      });

      test('should preserve non-preference exercise properties', () {
        final pref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
        );

        final modified = pref.applyToExercise(testExercise);

        expect(modified.id, equals(testExercise.id));
        expect(modified.name, equals(testExercise.name));
        expect(modified.category, equals(testExercise.category));
        expect(modified.targetMuscleGroups,
            equals(testExercise.targetMuscleGroups));
        expect(modified.isDefault, equals(testExercise.isDefault));
      });
    });

    group('copyWith', () {
      late UserExercisePreferences originalPref;

      setUp(() {
        originalPref = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
          preferredReps: 5,
          preferredWeight: 225.0,
          preferredRestTimeSeconds: 120,
          notes: 'Original notes',
        );
      });

      test('should create copy with updated preferredSets', () {
        final copy = originalPref.copyWith(preferredSets: 8);

        expect(copy.preferredSets, equals(8));
        expect(copy.preferredReps, equals(5)); // unchanged
        expect(copy.exerciseId, equals('bench')); // unchanged
      });

      test('should create copy with updated preferredReps', () {
        final copy = originalPref.copyWith(preferredReps: 10);

        expect(copy.preferredReps, equals(10));
        expect(copy.preferredSets, equals(5)); // unchanged
      });

      test('should create copy with updated preferredWeight', () {
        final copy = originalPref.copyWith(preferredWeight: 315.0);

        expect(copy.preferredWeight, equals(315.0));
      });

      test('should create copy with updated preferredRestTimeSeconds', () {
        final copy = originalPref.copyWith(preferredRestTimeSeconds: 180);

        expect(copy.preferredRestTimeSeconds, equals(180));
      });

      test('should create copy with updated notes', () {
        final copy = originalPref.copyWith(notes: 'Updated notes');

        expect(copy.notes, equals('Updated notes'));
      });

      test('should preserve id when copying', () {
        final copy = originalPref.copyWith(preferredSets: 10);

        expect(copy.id, equals(originalPref.id));
      });

      test('should preserve exerciseId when copying', () {
        final copy = originalPref.copyWith(preferredSets: 10);

        expect(copy.exerciseId, equals(originalPref.exerciseId));
      });

      test('should preserve createdAt when copying', () {
        final copy = originalPref.copyWith(preferredSets: 10);

        expect(copy.createdAt, equals(originalPref.createdAt));
      });

      test('should update updatedAt when copying', () {
        // Small delay to ensure different timestamp
        final copy = originalPref.copyWith(
          preferredSets: 10,
          updatedAt: DateTime.now().add(const Duration(seconds: 1)),
        );

        expect(copy.updatedAt.isAfter(originalPref.updatedAt), isTrue);
      });

      test('should not modify original when copying', () {
        originalPref.copyWith(preferredSets: 10);

        expect(originalPref.preferredSets, equals(5));
      });
    });

    group('JSON Serialization', () {
      test('toJson should serialize all fields', () {
        final pref = UserExercisePreferences(
          id: 'pref_123',
          exerciseId: 'bench',
          preferredSets: 5,
          preferredReps: 5,
          preferredWeight: 225.0,
          preferredRestTimeSeconds: 120,
          notes: 'Test notes',
          createdAt: DateTime.utc(2025, 1, 1, 12, 0, 0),
          updatedAt: DateTime.utc(2025, 1, 2, 12, 0, 0),
        );

        final json = pref.toJson();

        expect(json['id'], equals('pref_123'));
        expect(json['exerciseId'], equals('bench'));
        expect(json['preferredSets'], equals(5));
        expect(json['preferredReps'], equals(5));
        expect(json['preferredWeight'], equals(225.0));
        expect(json['preferredRestTimeSeconds'], equals(120));
        expect(json['notes'], equals('Test notes'));
        expect(json['createdAt'], isNotNull);
        expect(json['updatedAt'], isNotNull);
      });

      test('fromJson should deserialize all fields', () {
        final json = {
          'id': 'pref_123',
          'exerciseId': 'bench',
          'preferredSets': 5,
          'preferredReps': 5,
          'preferredWeight': 225.0,
          'preferredRestTimeSeconds': 120,
          'notes': 'Test notes',
          'createdAt': '2025-01-01T12:00:00.000Z',
          'updatedAt': '2025-01-02T12:00:00.000Z',
        };

        final pref = UserExercisePreferences.fromJson(json);

        expect(pref.id, equals('pref_123'));
        expect(pref.exerciseId, equals('bench'));
        expect(pref.preferredSets, equals(5));
        expect(pref.preferredReps, equals(5));
        expect(pref.preferredWeight, equals(225.0));
        expect(pref.preferredRestTimeSeconds, equals(120));
        expect(pref.notes, equals('Test notes'));
      });

      test('fromJson should handle null optional fields', () {
        final json = {
          'id': 'pref_123',
          'exerciseId': 'bench',
          'createdAt': '2025-01-01T12:00:00.000Z',
          'updatedAt': '2025-01-02T12:00:00.000Z',
        };

        final pref = UserExercisePreferences.fromJson(json);

        expect(pref.preferredSets, isNull);
        expect(pref.preferredReps, isNull);
        expect(pref.preferredWeight, isNull);
        expect(pref.preferredRestTimeSeconds, isNull);
        expect(pref.notes, isNull);
      });

      test('round-trip serialization should preserve data', () {
        final original = UserExercisePreferences.create(
          exerciseId: 'bench',
          preferredSets: 5,
          preferredWeight: 225.0,
          notes: 'Round trip test',
        );

        final json = original.toJson();
        final restored = UserExercisePreferences.fromJson(json);

        expect(restored.id, equals(original.id));
        expect(restored.exerciseId, equals(original.exerciseId));
        expect(restored.preferredSets, equals(original.preferredSets));
        expect(restored.preferredWeight, equals(original.preferredWeight));
        expect(restored.notes, equals(original.notes));
      });
    });
  });
}
